### PR TITLE
Unused dependencies

### PR DESCRIPTION
**Pull request by abaracedo**
This PR removes some of the installed packages that are not used, probably there're other packages that can be removed.

The `devDependencies` object got sorted when removing the packages

### CODE REVIEW

**Comment by aminya** [comment]
Thanks for the contribution, however, atom-ide packages follow our template: https://github.com/atom-ide-community/atom-ide-template-js. We want to keep these consistent between packages, even if we are not using them. This does not affect the end-user. Thanks again and sorry about this! I hope to see your future contributions.

**Comment by abaracedo** [comment]
I understand, but I have to disagree trying to keep that consistency. I think it's not correct having multiple projects with the same packages even if they're not used. That means that if project A has a new package that's going to be used it also has to be installed in the other packages.

That is going to create a big `package.json` and any new contributor will be confused seeing that a project has a lot of dependencies not used and thinking if they're there for the future or if someone forgot to uninstall them.

**Comment by aminya** [comment]
@abaracedo These packages include developer tools (devDependencies) and they are not `dependencies`.  They include:
- rollup
- babel
- eslint
- ...

These devDependencies are the same for all the projects of this organization, and we do not want to spend time adjusting them for each separate package. That just makes upgrading the tools for each package harder. Currently, if we decide to use a new rollup plugin (like multi-entry), we just throw it there for all packages without being worried about who uses what. 

The least important thing for us is to create the size of node_modules or the number of devDependencie low. Regarding the confusion, JSON currently does not support comments, and NPM does not support extending. As long as Node and NPM do not provide a cleaner way to hide these, it does not worth it to put time on adapting dev deps for each individual package. This is similar to developer tools for other languages. For example, LLVM with at least 2GB has everything a developer needs for building C++ code. No developer will try to remove the parts of LLVM that they don't use.

I know this might sound counter-intuitive but it is a decision that is made already.

**Comment by abaracedo** [comment]
Makes sense, thanks for the clarification.

**Comment by aminya** [comment]
Thank you for understanding. Your contributions are still valuable to us, but in this particular case, we want to follow the template.

**Pull request closed without merging**
